### ISSUE TITLE
render version of the app on the website

### ISSUE THREAD

**Issue by staabm** [Dexecure/ruxt#10]
as a contributor we dont know when you do deployements. therefore it would be cool if in the footer of https://ruxt.dexecure.com/ would be mentioned a git commit hash (or version, in case you do proper tags/releases) so people know which of the contributed changes are already part of the website, and which are not.

**Comment by RatulSaha** [comment]
Thank you for the suggestion! We are planning to tag versions soon.

Please bear with us, we are working on some critical bugs, and it's holiday season - hence the speed. :-)

**Comment by inian** [comment]
Hey, I thought a better solution would be to carry out the development on the develop branch and track the version deployed on the website on the master branch. Updated README to reflect this - https://github.com/Dexecure/ruxt#contributing
