### ISSUE TITLE
Feature: Add several Urls and compare them

### ISSUE THREAD

**Issue by staabm** [Dexecure/ruxt#5]
would be great if one could define several page urls and the diagram/numbers below will turn into a compare view.

This could even make sense to compare 3,4 or 5 pages at once.

**Comment by RatulSaha** [comment]
Thank you for the feature request, it indeed is a very useful extension of the current stage.

We will put this feature in pipeline and close this accordingly, notifying you.

**Comment by inian** [comment]
We just implemented the ability to compare 2 URLS. Check it out :) - https://ruxt.dexecure.com/compare
